const ORIGIN_CURSOR_MENU_X = 116;
const ORIGIN_CURSOR_MENU_Y = 320;

const ORIGIN_CURSOR_PLAY_X = 208;
const ORIGIN_CURSOR_PLAY_Y = 410;

const ORIGIN_PLAYER_X = 800;
const ORIGIN_PLAYER_Y = 704;